---
- name: "Retrieve VPC information"
  amazon.aws.ec2_vpc_net_info:
    region: "{{ aws_region }}"
    filters:
      tag:purpose: "aa_ne"
  register: __vpc_info

- name: "Retrieve instance information"
  amazon.aws.ec2_instance_info:
    region: "{{ aws_region }}"
    filters:
      tag:purpose: "aa_ne"
  register: __instance_info

- name: "Retrieve IGW information"
  amazon.aws.ec2_vpc_igw_info:
    region: "{{ aws_region }}"
    filters:
      tag:purpose: "aa_ne"
  register: __igw_info

- name: "Grab boto3 version"
  ansible.builtin.set_fact:
    boto_version: >-
      "{{ lookup('pipe', ansible_playbook_python ~ ' -c "import boto3; print(boto3.__version__)"') }}"
