---
- name: "Set fact for working directory"
  ansible.builtin.set_fact:
    __report_workdir: "{{ ansible_env.HOME }}/report_workdir"

- name: "Create working directory"
  ansible.builtin.file:
    path: "{{ __report_workdir }}"
    state: directory
    mode: 0755

- name: "Render template"
  ansible.builtin.template:
    src: "index.html.j2"
    dest: "{{ __report_workdir }}/index.html"
    mode: 0644

- name: "Create S3 bucket"
  amazon.aws.s3_bucket:
    name: "{{ cloud_report_publish_s3_bucket_name }}"
    state: present
    versioning: false
    tags:
      purpose: "aa_ne"

- name: "Configure S3 bucket for report hosting"
  community.aws.s3_website:
    name: "{{ cloud_report_publish_s3_bucket_name }}"
    region: "{{ aws_region }}"
    state: present
    suffix: "index.html"

- name: "Copy static files to bucket"
  community.aws.s3_sync:
    bucket: "{{ cloud_report_publish_s3_bucket_name }}"
    file_root: "files/"
    permission: "public-read"
