---
- name: "Retrieve network information"
  openstack.cloud.networks_info:
  register: __os_net_info

- name: "Debug output"
  ansible.builtin.debug:
    var: __os_net_info

- name: "Retrieve subnet information"
  openstack.cloud.subnets_info:
  register: __os_subnet_info

- name: "Retrieve instance information"
  openstack.cloud.server_info:
  register: __os_server_info

- name: "Debug output"
  ansible.builtin.debug:
    var: __os_server_info

- name: "Retrieve config information"
  openstack.cloud.config:
  register: __os_config
