---
- name: "Fail if image is not found"
  ansible.builtin.assert:
    that:
      - "{{ azure_instance_os in azure_images }}"
    success_msg: "Valid image provided."
    fail_msg: "Invalid image provided. Bailing out."

- name: "Lookup image properties"
  ansible.builtin.set_fact:
    selected_image: "{{ azure_images[azure_instance_os] }}"

- name: "Debug output"
  ansible.builtin.debug:
    var: selected_image

- name: "Load OS-specific variables"
  ansible.builtin.include_vars:
    file: "{{ selected_image.os_type }}.yml"

- name: "Create instance"
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ azure_resourcegroup_name }}"
    name: "{{ '%s-%d' | format(azure_instance_name, idx) }}"
    vm_size: "{{ azure_instance_size }}"
    virtual_network_name: "{{ azure_instance_network_name }}"
    subnet_name: "{{ azure_instance_subnet_name | default(omit) }}"
    os_type: "{{ selected_image.os_type | capitalize }}"
    admin_username: "{{ azure_instance_admin_username }}"
    append_tags: "{{ azure_instance_purge_tags }}"
    ssh_password_enabled: "{{ azure_instance_ssh_password_enabled }}"
    ssh_public_keys:
      - path: "/home/{{ azure_instance_admin_username }}/.ssh/authorized_keys"
        key_data: "{{ azure_instance_pubkey }}"
    state: present
    image:
      offer: "{{ selected_image.offer }}"
      publisher: "{{ selected_image.publisher }}"
      sku: "{{ selected_image.sku }}"
      version: "{{ selected_image.version }}"
    custom_data: "{{ lookup('template', 'user_data.sh.j2') }}"
  loop: "{{ range(0, azure_instance_count) | list }}"
  loop_control:
    index_var: idx
  register: __azure_instance
  changed_when: not __azure_instance.changed
  async: 1000
  poll: 0

- name: "Wait for instances to finish creation"
  ansible.builtin.async_status:
    jid: "{{ __azure_instance_result_item.ansible_job_id }}"
  register: __azure_instance_result
  until: __azure_instance_result.finished
  retries: 100
  delay: 6
  loop: "{{ __azure_instance.results }}"
  loop_control:
    loop_var: __azure_instance_result_item
  when: __azure_instance_result_item.ansible_job_id is defined

- name: "Debug output"
  ansible.builtin.debug:
    var: __azure_instance
