---
- name: "Ensure Azure objects are configured"
  hosts: localhost
  become: false
  vars:
    azure_resource_state: "present"

  roles:
    - name: pumphouse_p.aa_ne.azure_net
      vars:
        azure_virtualnetwork_name: "aa_ne_net"
        azure_subnet_name: "aa_ne_subnet"

    - name: pumphouse_p.aa_ne.azure_instance
      vars:
        azure_instance_name: "aa-ne-azure-rhel"
        azure_instance_size: "Standard_B1ms"
        azure_instance_network_name: "aa_ne_net"
        azure_instance_subnet_name: "aa_ne_subnet"
        azure_instance_os: "rhel_8"