---
- name: "Ensure network resources are present"
  ansible.builtin.include_tasks:
    file: present.yml
  when: openstack_resource_state == 'present'

- name: "Ensure network resources are absent"
  ansible.builtin.include_tasks:
    file: absent.yml
  when: openstack_resource_state == 'absent'
