---
- name: "Ensure AWS objects are configured"
  hosts: localhost
  become: false
  vars:
    aws_resource_state: "present"

  roles:
    - name: pumphouse_p.aa_ne.aws_net
    - name: pumphouse_p.aa_ne.aws_key
      vars:
        aws_key_name: "aa_ne"
