---
galaxy_info:
  author: Devin Parrish
  role_name: openstack_net
  namespace: pumphouse_p.aa_ne
  description: Manages networking objects on an OpenStack cluster

  license: GPL

  min_ansible_version: 2.9

  galaxy_tags:
    - openstack
    - iaas
    - networking

  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

dependencies: []
