---
- name: "Open hardware change request"
  hosts: localhost
  become: false
  vars:
    snow_change_request_state: "open"

  pre_tasks:
    - name: "Initialize some vars when triggered via webhook"
      ansible.builtin.set_fact:
        short_description: >
          Apply "{{ awx_webhook_event_type }}" from SCM repo "{{ awx_webhook_payload.repository.url }}"
        long_description: |
          The user "{{ awx_webhook_payload.pusher.name }}" generated a "{{ awx_webhook_event_type }}" event on the SCM repo found at "{{ awx_webhook_payload.repository.url }}".

          The head commit was made by "{{ awx_webhook_payload.head_commit.author.name }}" at "{{ awx_webhook_payload.head_commit.timestamp }}".

          Head commit URL: "{{ awx_webhook_payload.head_commit.url }}"
          Head commit message: "{{ awx_webhook_payload.head_commit.message }}"

          Commit Log: "{{ awx_webhook_payload.commits | to_nice_json }}"
      when: awx_webhook_event_type is defined

    - name: "Initialize generic messages when not triggered via webhook"
      ansible.builtin.set_fact:
        short_description: "Hardware changes to be implemented"
        long_description: "Hardware changes have been requested."
      when: awx_webhook_event_type is not defined

  roles:
    - name: pumphouse_p.aa_ne.snow_change_request
      vars:
        snow_change_request_category: "hardware"
        snow_change_request_short_description: "{{ short_description }}"
        snow_change_request_description: "{{ long_description }}"
        snow_change_request_impact: "medium"
        snow_change_request_priority: "moderate"
        snow_change_request_risk: "low"
        snow_change_request_type: "normal"
        snow_change_request_urgency: "high"
