---
- name: "Open software change request"
  hosts: localhost
  become: false
  vars:
    snow_change_request_state: "open"

  roles:
    - name: pumphouse_p.aa_ne.snow_change_request
      vars:
        snow_change_request_category: "software"
        snow_change_request_short_description: >
          Apply common config
        snow_change_request_description: >
          Apply common configuration (install packages, configure OS, etc.) to cloud instances
        snow_change_request_impact: "medium"
        snow_change_request_priority: "moderate"
        snow_change_request_risk: "low"
        snow_change_request_type: "normal"
        snow_change_request_urgency: "high"
