---
- name: "Grab the ID of the VPC being operated on"
  amazon.aws.ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ vpc.name }}"
    region: "{{ aws_region }}"
  register: __vpc

- name: "Ensure a VPC has been found"
  ansible.builtin.assert:
    that:
      - __vpc.vpcs | length == 1
    success_msg: "Found {{ __vpc.vpcs | length }} VPC (id={{ __vpc.vpcs.0.id }})"
    fail_msg: "Did not find exactly 1 VPC. Bailing out."

- name: "Ensure subnet exists with desired configuration"
  amazon.aws.ec2_vpc_subnet:
    cidr: "{{ subnet.cidr_block }}"
    map_public: "{{ subnet.map_public }}"
    purge_tags: "{{ subnet.purge_tags }}"
    tags: "{{ __aws_net_default_tags | combine(subnet.tags) }}"
    vpc_id: "{{ __vpc.vpcs.0.id }}"
    region: "{{ aws_region }}"
    state: present
  loop: "{{ vpc.subnets }}"
  loop_control:
    loop_var: subnet

- name: "Ensure internet gateway exists when enabled"
  amazon.aws.ec2_vpc_igw:
    purge_tags: "{{ vpc.internet_gateway.purge_tags }}"
    tags: "{{ __aws_net_default_tags | combine(vpc.internet_gateway.tags) }}"
    vpc_id: "{{ __vpc.vpcs.0.id }}"
    region: "{{ aws_region }}"
    state: present
  when: vpc.internet_gateway
  register: __igw

- name: "Setup route table for public subnets"
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ __vpc.vpcs.0.id }}"
    region: "{{ aws_region }}"
    tags:
      Name: "aa-ne-public"
    subnets: "{{ vpc.subnets | selectattr('map_public') | map(attribute='cidr_block') | list }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ __igw.gateway_id }}"

- name: "Grab the ID(s) of the private subnets"
  amazon.aws.ec2_vpc_subnet_info:
    filters:
      "tag:Name": "{{ __subnet_id }}"
    region: "{{ aws_region }}"
  loop: "{{ vpc.subnets | rejectattr('map_public') | map(attribute=('tags.Name')) | list }}"
  loop_control:
    loop_var: __subnet_id
  register: __private_subnet_ids

- name: Debug output
  ansible.builtin.debug:
    var: __private_subnet_ids

- name: "Setup NAT gateways for private subnets"
  amazon.aws.ec2_vpc_nat_gateway:
    subnet_id: "{{ subnets.subnet_id }}"
    region: "{{ aws_region }}"
    state: present
  loop: "{{ __private_subnet_ids.results.subnets }}"
  loop_control:
    loop_var: subnets
